name: FertiLitef
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.9.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  model_viewer_plus: ^1.7.0
  path_provider: ^2.1.3
  http: ^1.2.2
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3
  csv: ^6.0.0
  file_picker: ^8.0.5
  intl: ^0.19.0
  flutter_gl: ^0.9.2
  three_dart:
    git:
      url: https://github.com/almin-li/three_dart.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/simulated_soil_square.csv
